### PR TITLE
Added --token-budget option

### PR DESCRIPTION
**Pull request by DaveDeCaprio**
As described in the docs:

  --token_budget TOKEN_BUDGET
                        Total budget in tokens for a singe CELI run, across all calls. If set to 0, there is no
                        budget. This only includes live calls, not cached calls. If the budget is exceeded, the run
                        will stop.

### CODE REVIEW

**Review by x3n0cr4735 — COMMENTED** [review]
Can we make it so that caching is defaulted when a token budget is set? Thinking someone might budget, run reaches limit and quits, and if whatever use wanted wasn't saved they need to rerun entirely if caching is not on

**Comment by DaveDeCaprio** [comment]
Caching is always defaulted on, so ai think we are ok.  You have to explicitly turn it off with —no-cache.DaveOn Jun 22, 2024, at 5:25 PM, Jan-Samuel Wagner ***@***.***> wrote:﻿
@x3n0cr4735 commented on this pull request.

Can we make it so that caching is defaulted when a token budget is set? Thinking someone might budget, run reaches limit and quits, and if whatever use wanted wasn't saved they need to rerun entirely if caching is not on

**Comment by x3n0cr4735** [comment]
I was thinking of my .env where I have it set up to not cache. If someone has NO_CACHE=True in .env maybe we can have a warning pop up? They may not think to change their .env when budgeting for their first time(s). Just as long as we do it in a way where it's not annoying. 

I also think we should default to have a budget set up to, say, 200k tokens (open to suggestions), so that worst case scenario someone doesn't run up millions of tokens without planning to.

We should also change the .env.example accordingly.

**Comment by DaveDeCaprio** [comment]
The doc now emphasizes command line arguments over the env file.  I’ve updated the .env.example to be very minimal.

 

Also, I’m not sure why you would want caching ever turned off on a regular basis.

 

The HUmanEval benchmark uses 9 million tokens, so I’m not sure what the right default budget would be.

 

Dave

**Comment by DaveDeCaprio** [comment]
@x3n0cr4735 Ok, I added a warning if caching is off and set the default budget to 10M tokens.

**Review by x3n0cr4735 — DISMISSED** [review]

**Comment by DaveDeCaprio** [comment]
@x3n0cr4735 There was a merge conflict so this needs to be approved again.

**Review by x3n0cr4735 — APPROVED** [review]

**Pull request merged**
